# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
# Orchestrate or schedule a set of jobs
commands:
  print_pipeline_id:
    description: "Print environment workspace id"
    steps:
      - run: echo $CIRCLE_WORKFLOW_ID

  
jobs:     
  invoke_command:
    docker: 
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id
            
workflows:
  # Name the workflow "welcome"
  begin:
    # Run the welcome/run job in its own container
    jobs:
      - invoke_command
      
